/**
 * TP ORCA AI — Framework Promotion Script
 *
 * Reads lib/frameworks/staging/irc-482.staging.yaml and writes
 * lib/frameworks/irc-482.ts with all extracted provisions.
 *
 * All provisions are promoted regardless of _review.status.
 * The _review block and source.rawText are stripped from the output.
 *
 * Usage:
 *   npx ts-node --compiler-options '{"module":"commonjs","moduleResolution":"node"}' scripts/promote-framework.ts
 *
 * After running:
 *   npx tsc --noEmit
 */

import fs from "fs";
import path from "path";

// ─── Config ───────────────────────────────────────────────────────────────────

const ROOT = path.resolve(process.cwd());

const STAGING_FILE = path.join(ROOT, "lib/frameworks/staging/irc-482.staging.yaml");
const OUTPUT_FILE  = path.join(ROOT, "lib/frameworks/irc-482.ts");

// Fields not stored in staging _meta — one entry per framework id.
const DOCUMENT_EXTRAS: Record<string, {
  shortName: string;
  jurisdiction: string[];
  tier: "mandatory" | "valuable";
}> = {
  "irc-482": { shortName: "IRC § 482", jurisdiction: ["US"], tier: "mandatory" },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

// "irc-482" → "irc482"  (valid JS identifier for the export const)
function toVarName(id: string): string {
  return id.replace(/-([a-z0-9])/gi, (_, c: string) => c);
}

type RawProvision = Record<string, unknown>;
type RawDoc       = Record<string, unknown>;

function stripProvision(raw: RawProvision): RawProvision {
  // Remove _review entirely.
  // Remove source.rawText — it's large and not part of FrameworkProvision.
  const { _review: _r, source, ...rest } = raw;
  void _r;

  const { rawText: _rt, ...cleanSource } = (source ?? {}) as Record<string, unknown>;
  void _rt;

  return { ...rest, source: cleanSource };
}

function indentLines(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line, i) => (i === 0 ? line : pad + line))
    .join("\n");
}

// ─── Code generator ───────────────────────────────────────────────────────────

function generateTs(doc: RawDoc): string {
  const meta    = doc._meta as Record<string, unknown>;
  const id      = meta.frameworkId as string;
  const extras  = DOCUMENT_EXTRAS[id];

  if (!extras) {
    throw new Error(
      `No DOCUMENT_EXTRAS entry for frameworkId "${id}". ` +
      `Add one to promote-framework.ts before promoting this framework.`
    );
  }

  const rawProvisions = (doc.provisions as RawProvision[]).map(stripProvision);
  const varName       = toVarName(id);

  // Serialize the provisions array as formatted JSON (valid TS).
  // Indent by 2 extra spaces so it nests cleanly inside the object literal.
  const provisionsJson = indentLines(
    JSON.stringify(rawProvisions, null, 2),
    2
  );

  const effectiveDate = String(meta.effectiveDate);

  return [
    `// Auto-generated by scripts/promote-framework.ts — do not edit by hand.`,
    `// Source    : ${meta.pdfSource}`,
    `// Extracted : ${meta.extractedAt}`,
    `// Promoted  : ${new Date().toISOString()}`,
    `import type { FrameworkDocument } from "./types";`,
    ``,
    `const ${varName}: FrameworkDocument = {`,
    `  id: ${JSON.stringify(id)},`,
    `  name: ${JSON.stringify(meta.frameworkName)},`,
    `  shortName: ${JSON.stringify(extras.shortName)},`,
    `  jurisdiction: ${JSON.stringify(extras.jurisdiction)},`,
    `  tier: ${JSON.stringify(extras.tier)},`,
    `  version: ${JSON.stringify(meta.version)},`,
    `  effectiveDate: ${JSON.stringify(effectiveDate)},`,
    `  provisions: ${provisionsJson},`,
    `};`,
    ``,
    `export default ${varName};`,
    ``,
  ].join("\n");
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main(): void {
  if (!fs.existsSync(STAGING_FILE)) {
    console.error(`Staging file not found:\n  ${STAGING_FILE}`);
    console.error(`Run scripts/extract-framework.ts first.`);
    process.exit(1);
  }

  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const yaml = require("js-yaml");
  const raw  = fs.readFileSync(STAGING_FILE, "utf-8");
  const doc  = yaml.load(raw) as RawDoc;

  const meta       = doc._meta as Record<string, unknown>;
  const provisions = doc.provisions as RawProvision[];

  console.log(`Framework  : ${meta.frameworkName}`);
  console.log(`Version    : ${meta.version}`);
  console.log(`Provisions : ${provisions.length}`);
  console.log(`Source     : ${meta.pdfSource}`);
  console.log();

  const ts = generateTs(doc);

  fs.writeFileSync(OUTPUT_FILE, ts, "utf-8");
  console.log(`Written: ${OUTPUT_FILE}`);
  console.log();
  console.log("Verify the build:");
  console.log("  npx tsc --noEmit");
}

main();
